include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    file_names: ignore
    deprecated_member_use: ignore
    unused_local_variable: ignore
    use_build_context_synchronously: ignore
    override_on_non_overriding_member: ignore
    curly_braces_in_flow_control_structures: ignore
    prefer_final_fields: ignore
    sort_child_properties_last: ignore
    camel_case_types: ignore
